var path       = require('path')
var fs         = require('fs')
var browserify = require('browserify')
var bundlePath = path.join("public", "libs.js")

browserify({debug: true})
  .require("async")
  .require("gl-mat3")
  .require("gl-mat4")
  .require("node-uuid")
  .bundle()
  .on('error', function (err) { console.error(err); })
  .pipe(fs.createWriteStream(bundlePath))
